// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetKeyValueRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetKeyValueRequest) Reset()         { *m = SetKeyValueRequest{} }
func (m *SetKeyValueRequest) String() string { return proto.CompactTextString(m) }
func (*SetKeyValueRequest) ProtoMessage()    {}
func (*SetKeyValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_661bd9cd37a3a4d8, []int{0}
}
func (m *SetKeyValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetKeyValueRequest.Unmarshal(m, b)
}
func (m *SetKeyValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetKeyValueRequest.Marshal(b, m, deterministic)
}
func (dst *SetKeyValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetKeyValueRequest.Merge(dst, src)
}
func (m *SetKeyValueRequest) XXX_Size() int {
	return xxx_messageInfo_SetKeyValueRequest.Size(m)
}
func (m *SetKeyValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetKeyValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetKeyValueRequest proto.InternalMessageInfo

func (m *SetKeyValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetKeyValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetKeyValueWithTTLRequest struct {
	Key                  string             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl                  *duration.Duration `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SetKeyValueWithTTLRequest) Reset()         { *m = SetKeyValueWithTTLRequest{} }
func (m *SetKeyValueWithTTLRequest) String() string { return proto.CompactTextString(m) }
func (*SetKeyValueWithTTLRequest) ProtoMessage()    {}
func (*SetKeyValueWithTTLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_661bd9cd37a3a4d8, []int{1}
}
func (m *SetKeyValueWithTTLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetKeyValueWithTTLRequest.Unmarshal(m, b)
}
func (m *SetKeyValueWithTTLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetKeyValueWithTTLRequest.Marshal(b, m, deterministic)
}
func (dst *SetKeyValueWithTTLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetKeyValueWithTTLRequest.Merge(dst, src)
}
func (m *SetKeyValueWithTTLRequest) XXX_Size() int {
	return xxx_messageInfo_SetKeyValueWithTTLRequest.Size(m)
}
func (m *SetKeyValueWithTTLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetKeyValueWithTTLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetKeyValueWithTTLRequest proto.InternalMessageInfo

func (m *SetKeyValueWithTTLRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetKeyValueWithTTLRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SetKeyValueWithTTLRequest) GetTtl() *duration.Duration {
	if m != nil {
		return m.Ttl
	}
	return nil
}

type SetKeyTTLRequest struct {
	Key                  string             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Ttl                  *duration.Duration `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SetKeyTTLRequest) Reset()         { *m = SetKeyTTLRequest{} }
func (m *SetKeyTTLRequest) String() string { return proto.CompactTextString(m) }
func (*SetKeyTTLRequest) ProtoMessage()    {}
func (*SetKeyTTLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_661bd9cd37a3a4d8, []int{2}
}
func (m *SetKeyTTLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetKeyTTLRequest.Unmarshal(m, b)
}
func (m *SetKeyTTLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetKeyTTLRequest.Marshal(b, m, deterministic)
}
func (dst *SetKeyTTLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetKeyTTLRequest.Merge(dst, src)
}
func (m *SetKeyTTLRequest) XXX_Size() int {
	return xxx_messageInfo_SetKeyTTLRequest.Size(m)
}
func (m *SetKeyTTLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetKeyTTLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetKeyTTLRequest proto.InternalMessageInfo

func (m *SetKeyTTLRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetKeyTTLRequest) GetTtl() *duration.Duration {
	if m != nil {
		return m.Ttl
	}
	return nil
}

type ValueResponse struct {
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueResponse) Reset()         { *m = ValueResponse{} }
func (m *ValueResponse) String() string { return proto.CompactTextString(m) }
func (*ValueResponse) ProtoMessage()    {}
func (*ValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_661bd9cd37a3a4d8, []int{3}
}
func (m *ValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueResponse.Unmarshal(m, b)
}
func (m *ValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueResponse.Marshal(b, m, deterministic)
}
func (dst *ValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueResponse.Merge(dst, src)
}
func (m *ValueResponse) XXX_Size() int {
	return xxx_messageInfo_ValueResponse.Size(m)
}
func (m *ValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValueResponse proto.InternalMessageInfo

func (m *ValueResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_661bd9cd37a3a4d8, []int{4}
}
func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (dst *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(dst, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetValuesResponse struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValuesResponse) Reset()         { *m = GetValuesResponse{} }
func (m *GetValuesResponse) String() string { return proto.CompactTextString(m) }
func (*GetValuesResponse) ProtoMessage()    {}
func (*GetValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_661bd9cd37a3a4d8, []int{5}
}
func (m *GetValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValuesResponse.Unmarshal(m, b)
}
func (m *GetValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValuesResponse.Marshal(b, m, deterministic)
}
func (dst *GetValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValuesResponse.Merge(dst, src)
}
func (m *GetValuesResponse) XXX_Size() int {
	return xxx_messageInfo_GetValuesResponse.Size(m)
}
func (m *GetValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValuesResponse proto.InternalMessageInfo

func (m *GetValuesResponse) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type ByKeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByKeyRequest) Reset()         { *m = ByKeyRequest{} }
func (m *ByKeyRequest) String() string { return proto.CompactTextString(m) }
func (*ByKeyRequest) ProtoMessage()    {}
func (*ByKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_661bd9cd37a3a4d8, []int{6}
}
func (m *ByKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByKeyRequest.Unmarshal(m, b)
}
func (m *ByKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByKeyRequest.Marshal(b, m, deterministic)
}
func (dst *ByKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByKeyRequest.Merge(dst, src)
}
func (m *ByKeyRequest) XXX_Size() int {
	return xxx_messageInfo_ByKeyRequest.Size(m)
}
func (m *ByKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByKeyRequest proto.InternalMessageInfo

func (m *ByKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*SetKeyValueRequest)(nil), "proto.SetKeyValueRequest")
	proto.RegisterType((*SetKeyValueWithTTLRequest)(nil), "proto.SetKeyValueWithTTLRequest")
	proto.RegisterType((*SetKeyTTLRequest)(nil), "proto.SetKeyTTLRequest")
	proto.RegisterType((*ValueResponse)(nil), "proto.ValueResponse")
	proto.RegisterType((*KeyValue)(nil), "proto.KeyValue")
	proto.RegisterType((*GetValuesResponse)(nil), "proto.GetValuesResponse")
	proto.RegisterType((*ByKeyRequest)(nil), "proto.ByKeyRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KeyValueStorageClient is the client API for KeyValueStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyValueStorageClient interface {
	Set(ctx context.Context, in *SetKeyValueRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SetWithTTL(ctx context.Context, in *SetKeyValueWithTTLRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SetTTL(ctx context.Context, in *SetKeyTTLRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetValue(ctx context.Context, in *ByKeyRequest, opts ...grpc.CallOption) (*ValueResponse, error)
	GetTTL(ctx context.Context, in *ByKeyRequest, opts ...grpc.CallOption) (*duration.Duration, error)
	GetValues(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetValuesResponse, error)
	Delete(ctx context.Context, in *ByKeyRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type keyValueStorageClient struct {
	cc *grpc.ClientConn
}

func NewKeyValueStorageClient(cc *grpc.ClientConn) KeyValueStorageClient {
	return &keyValueStorageClient{cc}
}

func (c *keyValueStorageClient) Set(ctx context.Context, in *SetKeyValueRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.KeyValueStorage/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStorageClient) SetWithTTL(ctx context.Context, in *SetKeyValueWithTTLRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.KeyValueStorage/SetWithTTL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStorageClient) SetTTL(ctx context.Context, in *SetKeyTTLRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.KeyValueStorage/SetTTL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStorageClient) GetValue(ctx context.Context, in *ByKeyRequest, opts ...grpc.CallOption) (*ValueResponse, error) {
	out := new(ValueResponse)
	err := c.cc.Invoke(ctx, "/proto.KeyValueStorage/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStorageClient) GetTTL(ctx context.Context, in *ByKeyRequest, opts ...grpc.CallOption) (*duration.Duration, error) {
	out := new(duration.Duration)
	err := c.cc.Invoke(ctx, "/proto.KeyValueStorage/GetTTL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStorageClient) GetValues(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetValuesResponse, error) {
	out := new(GetValuesResponse)
	err := c.cc.Invoke(ctx, "/proto.KeyValueStorage/GetValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStorageClient) Delete(ctx context.Context, in *ByKeyRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.KeyValueStorage/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyValueStorageServer is the server API for KeyValueStorage service.
type KeyValueStorageServer interface {
	Set(context.Context, *SetKeyValueRequest) (*empty.Empty, error)
	SetWithTTL(context.Context, *SetKeyValueWithTTLRequest) (*empty.Empty, error)
	SetTTL(context.Context, *SetKeyTTLRequest) (*empty.Empty, error)
	GetValue(context.Context, *ByKeyRequest) (*ValueResponse, error)
	GetTTL(context.Context, *ByKeyRequest) (*duration.Duration, error)
	GetValues(context.Context, *empty.Empty) (*GetValuesResponse, error)
	Delete(context.Context, *ByKeyRequest) (*empty.Empty, error)
}

func RegisterKeyValueStorageServer(s *grpc.Server, srv KeyValueStorageServer) {
	s.RegisterService(&_KeyValueStorage_serviceDesc, srv)
}

func _KeyValueStorage_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStorageServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyValueStorage/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStorageServer).Set(ctx, req.(*SetKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStorage_SetWithTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKeyValueWithTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStorageServer).SetWithTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyValueStorage/SetWithTTL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStorageServer).SetWithTTL(ctx, req.(*SetKeyValueWithTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStorage_SetTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKeyTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStorageServer).SetTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyValueStorage/SetTTL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStorageServer).SetTTL(ctx, req.(*SetKeyTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStorage_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStorageServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyValueStorage/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStorageServer).GetValue(ctx, req.(*ByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStorage_GetTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStorageServer).GetTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyValueStorage/GetTTL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStorageServer).GetTTL(ctx, req.(*ByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStorage_GetValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStorageServer).GetValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyValueStorage/GetValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStorageServer).GetValues(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStorage_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStorageServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.KeyValueStorage/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStorageServer).Delete(ctx, req.(*ByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyValueStorage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.KeyValueStorage",
	HandlerType: (*KeyValueStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _KeyValueStorage_Set_Handler,
		},
		{
			MethodName: "SetWithTTL",
			Handler:    _KeyValueStorage_SetWithTTL_Handler,
		},
		{
			MethodName: "SetTTL",
			Handler:    _KeyValueStorage_SetTTL_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _KeyValueStorage_GetValue_Handler,
		},
		{
			MethodName: "GetTTL",
			Handler:    _KeyValueStorage_GetTTL_Handler,
		},
		{
			MethodName: "GetValues",
			Handler:    _KeyValueStorage_GetValues_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KeyValueStorage_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_pb_661bd9cd37a3a4d8) }

var fileDescriptor_pb_661bd9cd37a3a4d8 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x51, 0x4b, 0xc2, 0x50,
	0x14, 0xc7, 0x99, 0xc3, 0xa1, 0xa7, 0x22, 0xbb, 0x89, 0xcd, 0x05, 0x31, 0x06, 0x81, 0x20, 0x4c,
	0x30, 0x04, 0x83, 0x7a, 0x09, 0xcb, 0x07, 0x7b, 0x69, 0x93, 0x7a, 0x56, 0x3a, 0x99, 0xb4, 0xbc,
	0xcb, 0x9d, 0x05, 0xfb, 0x60, 0x7d, 0xbf, 0xd8, 0xee, 0x9d, 0x68, 0xeb, 0xc6, 0x7a, 0xd2, 0x73,
	0xcf, 0x39, 0xbf, 0x73, 0xfe, 0xe7, 0x3f, 0xa8, 0x85, 0x73, 0x37, 0x5c, 0x73, 0xe2, 0xac, 0x9a,
	0xfd, 0x58, 0x67, 0x0b, 0xce, 0x17, 0x01, 0xf6, 0xb2, 0x68, 0x1e, 0xbf, 0xf4, 0x9e, 0xe3, 0xf5,
	0x8c, 0x96, 0x7c, 0x25, 0xca, 0xac, 0xd3, 0x9f, 0x79, 0x7c, 0x0f, 0x29, 0x11, 0x49, 0xe7, 0x0a,
	0x98, 0x8f, 0x34, 0xc1, 0xe4, 0x71, 0x16, 0xc4, 0xe8, 0xe1, 0x47, 0x8c, 0x11, 0xb1, 0x06, 0xe8,
	0x6f, 0x98, 0x98, 0x9a, 0xad, 0x75, 0xea, 0x5e, 0xfa, 0x97, 0x35, 0xa1, 0xfa, 0x99, 0x56, 0x98,
	0x95, 0xec, 0x4d, 0x04, 0x4e, 0x08, 0xed, 0xad, 0xee, 0xa7, 0x25, 0xbd, 0x4e, 0xa7, 0xf7, 0xff,
	0x84, 0xb0, 0x2e, 0xe8, 0x44, 0x81, 0xa9, 0xdb, 0x5a, 0x67, 0xaf, 0xdf, 0x76, 0xc5, 0xb6, 0x6e,
	0xbe, 0xad, 0x3b, 0x92, 0x6a, 0xbc, 0xb4, 0xca, 0x79, 0x80, 0x86, 0x98, 0xf8, 0xe7, 0x20, 0x89,
	0xac, 0x94, 0x42, 0x9e, 0xc3, 0x81, 0x14, 0x1f, 0x85, 0x7c, 0x15, 0xa1, 0x42, 0x6b, 0x1f, 0x6a,
	0xb9, 0xd0, 0xd2, 0xf7, 0xe9, 0xc2, 0xd1, 0x18, 0x29, 0xeb, 0x89, 0x36, 0xf8, 0x16, 0x18, 0x59,
	0x36, 0x32, 0x35, 0x5b, 0xef, 0xd4, 0x3d, 0x19, 0x39, 0x36, 0xec, 0xdf, 0x24, 0x13, 0x4c, 0x94,
	0xb2, 0xfa, 0x5f, 0x3a, 0x1c, 0xe6, 0x3b, 0xf8, 0xc4, 0xd7, 0xb3, 0x05, 0xb2, 0x21, 0xe8, 0x3e,
	0x12, 0x6b, 0x0b, 0x75, 0x6e, 0xd1, 0x4c, 0xab, 0x55, 0xd0, 0x7f, 0x9b, 0x7e, 0x00, 0xec, 0x0e,
	0xc0, 0x47, 0x92, 0xa6, 0x31, 0xbb, 0x08, 0xd8, 0xf5, 0x53, 0xc9, 0xb9, 0x04, 0xc3, 0x47, 0x4a,
	0x19, 0x27, 0x3b, 0x8c, 0x12, 0xad, 0x03, 0xa8, 0xe5, 0xf7, 0x61, 0xc7, 0xb2, 0x79, 0xfb, 0x06,
	0x56, 0x53, 0x3e, 0xee, 0x1a, 0x34, 0x04, 0x63, 0x2c, 0x26, 0xfe, 0xda, 0xa4, 0x36, 0x9c, 0x5d,
	0x43, 0x7d, 0x63, 0x08, 0x53, 0x6c, 0x65, 0x99, 0x12, 0x5a, 0xb4, 0x6e, 0x00, 0xc6, 0x08, 0x03,
	0x24, 0xc5, 0xb6, 0x0a, 0xe0, 0xdc, 0xc8, 0xe2, 0x8b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xad,
	0xd7, 0xb0, 0x31, 0xbb, 0x03, 0x00, 0x00,
}
